[package]
name = "minigrep"
version = "0.1.0"
authors = ["leo_hu"]
description = "The Rust Programming Language Chapter 12 minigrep"
license = "MIT OR Apache-2.0"

[dependencies]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
